[package]
name = "pppm"
version = "0.1.0"
authors = ["Shinichi Kogai <kogai0121@gmail.com>"]

# [[bin]]
# name = "main"
# path = "src/main.rs"

# [[bin]]
# name = "example"
# path = "src/example.rs"

[dependencies]
# bincode = "~0.9.2"
# config_file_handler = "~0.8.0"
# crust = { git = "https://github.com/maidsafe/crust", branch = "dev" }
# env_logger = "~0.4.3"
# future-utils = "~0.9.0"
# futures = "~0.1.17"
# get_if_addrs = "~0.4.0"
# log = "~0.3.8"
# lru_time_cache = "~0.8.0"
# maidsafe_utilities = "~0.15.0"
# maplit = "~1.0.1"
# net-literals = "~0.1"
# net2 = "~0.2.31"
# notify = "~4.0.1"
# quick-error = "~1.2.0"
# rand = "~0.3.17"
# rand_derive = "~0.3.1"
# rust_sodium = "~0.7"
# serde = "~1.0.10"
# serde_derive = "~1.0.10"
# serde_json = "~1.0.2"
# tiny-keccak = "~1.3"
# tokio-core = "~0.1.10"
# tokio-io = "~0.1.3"
# tokio-utp = "~0.3.0"
# unwrap = "~1.1"
# url = "~1.5.1"
# void = "~1.0.2"
clap = "~2.31.1"

# [features]
# clap = ["yaml"]

# [dependencies.bytes]
# features = ["serde"]
# version = "~0.4"

# [dependencies.p2p]
# git = "https://github.com/ustulation/p2p"
# rev = "ee0f536848a9bed36d2183f1dff8ec14f8f50d6d"

# [dev-dependencies]
# chrono = "~0.4.0"
# hamcrest = "~0.1.5"

# [target.'cfg(target_os = "linux")'.dependencies]
# netsim = { version = "~0.1.9", optional = true }

# [features]
# default = ["netsim"]
